// auto-generated from build.rs

#![allow(non_camel_case_types)]
use primitive_enum::primitive_enum;
primitive_enum! { ExplosionType i8 ;
    Grenade,
    Grenadelauncher,
    Stickybomb,
    Molotov,
    Rocket,
    Tankshell,
    HiOctane,
    Car,
    Plane,
    PetrolPump,
    Bike,
    DirSteam,
    DirFlame,
    DirWaterHydrant,
    DirGasCanister,
    Boat,
    ShipDestroy,
    Truck,
    Bullet,
    Smokegrenadelauncher,
    Smokegrenade,
    Bzgas,
    Flare,
    GasCanister,
    Extinguisher,
    Programmablear,
    Train,
    Barrel,
    Propane,
    Blimp,
    DirFlameExplode,
    Tanker,
    PlaneRocket,
    VehicleBullet,
    GasTank,
    Firework,
    Snowball,
    Proxmine,
    ValkyrieCannon,
    Unknown = -1,
}