[package]
name = "cargo-altvup"
version = "0.3.7"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
description = "Rust module + alt:V server installer"

[[bin]]
name = "cargo-altvup"

[dependencies]
colored = "2.0.0"
flate2 = "1.0.34"
serde.workspace = true
tar = "0.4.43"
anyhow.workspace = true
sha1_smol = "1.0.1"

[dependencies.ureq]
version = "2.10.1"
features = ["json"]

[lints.clippy]
unwrap_used = "forbid"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/altvup-release-v{ version }/{ target }{ archive-suffix }"
bin-dir = "{ bin }{ format }"
