[package]
name = "altv_internal_core_shared"
description = "An internal crate for alt:V module. Not intended for direct use."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
rust-version.workspace = true

[dependencies]
altv_sdk = { path = "../altv_sdk", package = "altv_internal_sdk", version = "=16.4.3" }
anyhow.workspace = true
