[package]
name = "wasm_bindgen"
version = { workspace = true }
edition = { workspace = true }

[lib]
proc-macro = true

[dependencies]
quote = { workspace = true }
syn = { workspace = true }
proc-macro2 = { workspace = true }
