# TODO: remove this file

name: test-release

on:
  push:
    tags:
      - 'test-release-v*'

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: extract version from tag
        run: |
          VERSION=$( echo ${{ github.ref_name }} | grep -oP 'test-release-v\K.*' )
          echo $VERSION
      - name: print again
        run: echo $VERSION
      
      # - name: create archive
      #   # seems like --exclude-from doesnt support all syntax of gitignore but it doesnt really matter
      #   run: |
      #     cd ..
      #     tar --exclude-caches --exclude-vcs --exclude-from=./altv-rust/.gitignore --exclude=*.bat --exclude *.sh --directory ./altv-rust -czvf source.tar.gz .
      #     cp source.tar.gz ./altv-rust/source.tar.gz

      # - uses: ncipollo/release-action@v1
      #   id: create_release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      # - name: upload archive
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     asset_name: source.tar.gz
      #     file: source.tar.gz
      #     tag: ${{ github.ref }}
      #     overwrite: true
