name: Test

on:
  push:
    branches: "*"
  pull_request:

jobs:
  test-windows:
    runs-on: windows-2022

    if: ${{ !startsWith(github.event.head_commit.message, 'release new version:') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install latest stable rust
        run: rustup update
          
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Clang version
        run: |
          clang --version
      - name: Install winget
        run: |
          $progressPreference = 'silentlyContinue'
          Write-Information "Downloading WinGet and its dependencies..."
          Invoke-WebRequest -Uri https://aka.ms/getwinget -OutFile Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
          Invoke-WebRequest -Uri https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx -OutFile Microsoft.VCLibs.x64.14.00.Desktop.appx
          Invoke-WebRequest -Uri https://github.com/microsoft/microsoft-ui-xaml/releases/download/v2.8.6/Microsoft.UI.Xaml.2.8.x64.appx -OutFile Microsoft.UI.Xaml.2.8.x64.appx
          Add-AppxPackage Microsoft.VCLibs.x64.14.00.Desktop.appx
          Add-AppxPackage Microsoft.UI.Xaml.2.8.x64.appx
          Add-AppxPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle

      - name: Update
        run: |
          winget install LLVM.LLVM --silent --accept-source-agreements

      - name: Clang version again
        run: |
          clang --version
          
      - name: build
        shell: cmd
        # temp workaround https://github.com/google/autocxx/issues/1327
        run: |
          echo %PATH%
          set PATH=%PATH:C:\Program Files\LLVM\bin;=%
          echo %PATH%

          cargo build -vv
